apiVersion: v1 # Pod or service.  apps/v1 for deployment, or replica set, etc.
kind: Pod
metadata:
  name: super-basic-pod # Name of the pod.  Must be unique within the namespace.
  labels:
    app: super-basic-pod # Label for the pod.  Can be used to select the pod for services, etc.
    type: frontend # Label for the pod.  Can be used to select the pod for services, etc.
spec: # Specification of the pod.  Contains the containers, volumes, etc.
  containers: # List of containers in the pod.  A pod can have multiple containers, but in this case we only have one.
  - name: nginx # Name of the container.  Must be unique within the pod.
    image: nginx:latest # Docker image to use for the container. Docker Hub will be used to pull the image if it is not available locally.
                        # if not dockerhub put in the full path to the image, e.g. myregistry.com/myimage:tag